# Generated by Django 5.0.3 on 2024-04-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
    ]
