# Generated by Django 5.0.3 on 2024-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanagement", "0002_alter_user_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
