# Generated by Django 5.0.3 on 2024-04-19 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanagement", "0005_alter_task_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_type",
            new_name="firstname",
        ),
    ]
