# Generated by Django 5.0.3 on 2024-04-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanagement", "0006_rename_user_type_user_firstname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
