# Generated by Django 5.0.3 on 2024-04-20 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanagement", "0007_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
