# Generated by Django 5.0.3 on 2024-04-20 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanagement", "0008_task_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
