# Generated by Django 5.0.3 on 2024-04-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanagement", "0011_alter_task_end_date_alter_task_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
