# Generated by Django 5.0.3 on 2024-04-20 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanagement", "0012_alter_task_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="start_date",
        ),
    ]
