# Generated by Django 5.0.3 on 2024-04-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanagement", "0013_remove_task_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
