# Generated by Django 5.0.3 on 2024-04-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanagement", "0014_alter_task_description_alter_task_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="created_at",
            new_name="created_date",
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
