# Generated by Django 5.0.3 on 2024-04-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanagement", "0016_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
